In [32]:
import pandas as pd
from sklearn.svm import SVC, SVR
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score, silhouette_score
import numpy as np

In [2]:
df = pd.read_csv('auto.csv')

In [3]:
df.head()

cylinders  displacement  horsepower  weight  acceleration  model_year  \
0          8         307.0       130.0  3504.0          12.0          70   
1          8         350.0       165.0  3693.0          11.5          70   
2          8         318.0       150.0  3436.0          11.0          70   
3          8         304.0       150.0  3433.0          12.0          70   
4          8         302.0       140.0  3449.0          10.5          70   

   origin   mpg  
0       1  18.0  
1       1  15.0  
2       1  18.0  
3       1  16.0  
4       1  17.0

In [4]:
df.describe()

cylinders  displacement  horsepower       weight  acceleration  \
count  392.000000    392.000000  392.000000   392.000000    392.000000   
mean     5.471939    194.411990  104.469388  2977.584184     15.541327   
std      1.705783    104.644004   38.491160   849.402560      2.758864   
min      3.000000     68.000000   46.000000  1613.000000      8.000000   
25%      4.000000    105.000000   75.000000  2225.250000     13.775000   
50%      4.000000    151.000000   93.500000  2803.500000     15.500000   
75%      8.000000    275.750000  126.000000  3614.750000     17.025000   
max      8.000000    455.000000  230.000000  5140.000000     24.800000   

       model_year      origin         mpg  
count  392.000000  392.000000  392.000000  
mean    75.979592    1.576531   23.445918  
std      3.683737    0.805518    7.805007  
min     70.000000    1.000000    9.000000  
25%     73.000000    1.000000   17.000000  
50%     76.000000    1.000000   22.750000  
75%     79.000000    2.000000   29.000000  
max     82.000000    3.000000   46.600000

In [6]:
X = df[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin']]
y = df['mpg']

le = LabelEncoder()
for i in X.columns:
    X[i] = le.fit_transform(X[i])

y = le.fit_transform(y)

<ipython-input-6-baa9597ed1c3>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i] = le.fit_transform(X[i])


In [7]:
X

cylinders  displacement  horsepower  weight  acceleration  model_year  \
0            4            68          60     242            13           0   
1            4            71          78     260            11           0   
2            4            69          72     236             6           0   
3            4            66          72     235            13           0   
4            4            65          67     239             5           0   
..         ...           ...         ...     ...           ...         ...   
387          1            40          32     158            43          12   
388          1            17           3      53            93          12   
389          1            39          30      88            12          12   
390          1            33          25     134            71          12   
391          1            32          28     150            76          12   

     origin  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
387       0  
388       1  
389       0  
390       0  
391       0  

[392 rows x 7 columns]

In [8]:
y

array([ 17,   7,  17,   9,  13,   7,   5,   5,   5,   7,   7,   5,   7,
         5,  48,  38,  17,  34,  62,  57,  52,  48,  52,  57,  34,   1,
         1,   2,   0,  62,  67,  52,  22,   9,  13,  22,  17,   5,   5,
         5,   5,   3,   4,   4,  17,  38,  22,  17,  42,  67,  75,  75,
        79, 104,  62,  57,  48,  52,  42,  28,  34,   4,   5,   7,   5,
        13,   2,   4,   3,   4,  22,   7,   4,   4,   5,  17,  38,  34,
        57,  38,  67,  42,  67,  62,   4,   5,   4,   5,   7,   3,   4,
         4,   5,   4,   3,   4,  17,   9,  17,  17,  42,  57,   2,   3,
         4,   3,  17,  28,  34,  38,  17,  22,  34,  57,   7,   9,  71,
        48,  28,  22,   7,  48,  28,   2,  28,  22,   7,  79,  57,  85,
        52,   9,   9,  17,   9,   4,   5,   5,   5,  71,  57,  57,  79,
        85,  67,  48,  57,  48,  57,  79,  22,  17,   7,   7,   9,   7,
         9,   5,  13,   9,   7,  17,  34,  28,   4,  71,  42,  28,  42,
        48,  52,  48,  17,  71,  22,  42,  42,  38,  52,  93,  6

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [10]:
clf= SVR(kernel='rbf')
clf.fit(X_train,y_train)

SVR()

In [17]:
y_pred = clf.predict(X_test)

In [18]:
explained_variance_score(y_test, y_pred)

0.704168054520607

# Clustering

In [109]:
from sklearn.cluster import KMeans

In [110]:
df_crime = pd.read_csv('crime_data.csv')

In [111]:
df_crime.head()

State  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [112]:
df_crime.describe()

Murder     Assault   UrbanPop       Rape
count  50.00000   50.000000  50.000000  50.000000
mean    7.78800  170.760000  65.540000  21.232000
std     4.35551   83.337661  14.474763   9.366385
min     0.80000   45.000000  32.000000   7.300000
25%     4.07500  109.000000  54.500000  15.075000
50%     7.25000  159.000000  66.000000  20.100000
75%    11.25000  249.000000  77.750000  26.175000
max    17.40000  337.000000  91.000000  46.000000

In [113]:
X = df_crime[['Murder', 'Assault', 'UrbanPop', 'Rape']]
y = df_crime.State

In [114]:
kmean = KMeans(n_clusters=3, random_state=0).fit(X)

In [115]:
targets = set(kmean.labels_)

In [116]:
targets

{0, 1, 2}

In [117]:
silhouette_score(X, kmean.labels_)

0.5319024108339817

In [118]:
kmean.cluster_centers_

array([[  4.27      ,  87.55      ,  59.75      ,  14.39      ],
       [ 11.8125    , 272.5625    ,  68.3125    ,  28.375     ],
       [  8.21428571, 173.28571429,  70.64285714,  22.84285714]])

In [119]:
clusters = {x:[] for x in targets}
for i,v in enumerate(kmean.labels_):
    clusters[v].append(y[i])
    

In [120]:
for i in clusters:
    print(f'Cluster {i}')
    print(f'Centroide: {kmean.cluster_centers_[i]}')
    print(clusters[i])

Cluster 0
Centroide: [ 4.27 87.55 59.75 14.39]
['Connecticut', 'Hawaii', 'Idaho', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Maine', 'Minnesota', 'Montana', 'Nebraska', 'New Hampshire', 'North Dakota', 'Ohio', 'Pennsylvania', 'South Dakota', 'Utah', 'Vermont', 'West Virginia', 'Wisconsin']
Cluster 1
Centroide: [ 11.8125 272.5625  68.3125  28.375 ]
['Alabama', 'Alaska', 'Arizona', 'California', 'Delaware', 'Florida', 'Illinois', 'Louisiana', 'Maryland', 'Michigan', 'Mississippi', 'Nevada', 'New Mexico', 'New York', 'North Carolina', 'South Carolina']
Cluster 2
Centroide: [  8.21428571 173.28571429  70.64285714  22.84285714]
['Arkansas', 'Colorado', 'Georgia', 'Massachusetts', 'Missouri', 'New Jersey', 'Oklahoma', 'Oregon', 'Rhode Island', 'Tennessee', 'Texas', 'Virginia', 'Washington', 'Wyoming']


# Theano

In [125]:
import math

In [126]:
trX = np.linspace(-1, 1, 101)
trY = np.linspace(-1, 1, 101)
for i in range(len(trY)):
    trY[i] = math.log(1 + 0.5 * abs(trX[i])) + trX[i] / 3 + np.random.randn() * 0.033

In [127]:
trX

array([-1.  , -0.98, -0.96, -0.94, -0.92, -0.9 , -0.88, -0.86, -0.84,
       -0.82, -0.8 , -0.78, -0.76, -0.74, -0.72, -0.7 , -0.68, -0.66,
       -0.64, -0.62, -0.6 , -0.58, -0.56, -0.54, -0.52, -0.5 , -0.48,
       -0.46, -0.44, -0.42, -0.4 , -0.38, -0.36, -0.34, -0.32, -0.3 ,
       -0.28, -0.26, -0.24, -0.22, -0.2 , -0.18, -0.16, -0.14, -0.12,
       -0.1 , -0.08, -0.06, -0.04, -0.02,  0.  ,  0.02,  0.04,  0.06,
        0.08,  0.1 ,  0.12,  0.14,  0.16,  0.18,  0.2 ,  0.22,  0.24,
        0.26,  0.28,  0.3 ,  0.32,  0.34,  0.36,  0.38,  0.4 ,  0.42,
        0.44,  0.46,  0.48,  0.5 ,  0.52,  0.54,  0.56,  0.58,  0.6 ,
        0.62,  0.64,  0.66,  0.68,  0.7 ,  0.72,  0.74,  0.76,  0.78,
        0.8 ,  0.82,  0.84,  0.86,  0.88,  0.9 ,  0.92,  0.94,  0.96,
        0.98,  1.  ])

In [128]:
trY

array([ 0.02939471,  0.04121257,  0.05168382,  0.06978989,  0.08146777,
        0.07089378,  0.08179369,  0.11414044,  0.05506349,  0.04395219,
        0.04192512,  0.11131884,  0.08486622,  0.10746441,  0.03930775,
        0.08322604,  0.09344024,  0.04045019,  0.07840487,  0.03159674,
        0.08518105,  0.0823376 ,  0.06509217,  0.0752729 ,  0.02801662,
        0.02477448,  0.04587938,  0.06603117,  0.09543559,  0.0507668 ,
        0.01828823,  0.09318899,  0.0297016 ,  0.0408721 ,  0.09335047,
       -0.00400872,  0.08348554, -0.00168235,  0.00891354,  0.04769851,
        0.03448665, -0.01594512,  0.01179711, -0.00511677,  0.01149194,
       -0.01381996, -0.00860192,  0.0976808 ,  0.01551055,  0.00459984,
       -0.02586112,  0.01610712,  0.01549794,  0.09384599,  0.01958418,
        0.05157576,  0.09170034,  0.1554857 ,  0.14730196,  0.15268594,
        0.17955451,  0.1638391 ,  0.15774539,  0.16005844,  0.20512932,
        0.23397161,  0.26304464,  0.25550077,  0.28856596,  0.31