In [2]:
import numpy as np

In [54]:
def pibote(tabla):
    #multiplica por -1 la primera fila
    tabla[0,:]*=-1
    print(tabla)
    #guarda el minimo valor de la primera fila
    min_ = tabla[0,:].argmin()
    #print(min_)
    #determina columna pibote
    col_pib = tabla[:,min_]#[1:]
    # obtiene columna del lado derecho
    col_LD = tabla[:,-1]#[1:]
    # hace división para obtener el mínimo
    div = col_LD//col_pib
    # obtinene el índice del mínimo
    print(div)
    #update numpy for use np.amin with initial argument
    index_min = np.where(div == np.amin(div, initial=1))
    
    return index_min

def ops(tabla, pib):
    fila = tabla[pib,:]
    return fila
    

In [55]:
matriz = []
with open('modelo.txt', 'r') as f:
	lineas = f.readlines()
	for i in lineas:
		n = []
		for s in i.split():
			if s.isdigit():
				n.append(int(s))
		matriz.append(n)
#agraga un cero a la primera fila -z=0
matriz[:][0].append(0)
#elimina el último cero 
matriz.remove([0])
#print(matriz)

tabla = np.array(matriz)
p = pibote(tabla)
print(p)
#ops(tabla,p)

[[-4000 -3000 -2000     0]
 [    3     3     1    24]
 [    6     4     3    60]
 [    1     1     1    12]]
[ 0  8 10 12]


TypeError: amin() got an unexpected keyword argument 'initial'

In [56]:
help(np.amin)

Help on function amin in module numpy.core.fromnumeric:

amin(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the minimum of an array or minimum along an axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, the minimum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See `doc.ufuncs` (Section "Output arguments") for more details.
    
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
